drop type if exists grocery;
create type grocery as enum(
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

drop table if exists shopping_list;
create table if not exists shopping_list (
    id integer primary key generated by default as identity,
    name text not null,
    price numeric(12,2) not null,
    date_added timestamp default now() not null,
    checked boolean default 'f' not null,
    category grocery
);